spring.application.name=quiz-service
server.port=8090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/QuizDB
spring.datasource.username=postgres
spring.datasource.password=1234567890

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.questionService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.questionService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.questionService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.questionService.permittedNumberOfCallsInHalfOpenState=3

# Actuator Endpoints
management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always


resilience4j.ratelimiter.instances.quizService.limitForPeriod=5
resilience4j.ratelimiter.instances.quizService.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.quizService.timeoutDuration=0

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin